### ISSUE TITLE
MDN JS: Constructor is not being called properly

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/zeroclickinfo-fathead#369]
See the first line in the snippet. @MariagraziaAlastra @moollaza 

<img width="915" alt="screen shot 2016-09-12 at 2 13 09 pm" src="https://cloud.githubusercontent.com/assets/81969/18447113/3ca457d2-78f3-11e6-9887-6ad62269d8b3.png">

https://duck.co/ia/view/mdnjs

**Comment by MariagraziaAlastra** [comment]
Fixed now thanks to @bfmags

**Comment by bfmags** [comment]
Hi @jagtalon thanks for opening this issue.

The entry for the Date article in `output.txt` file contains the correct code :

`Date    A                                        <pre><code>new Date();\nnew Date(value);\nnew Date(dateString);\nnew Date(year, month[, day[, hour[, minutes[, seconds[, milliseconds]]]]]);\n</code></pre>Creates a JavaScript Date instance that represents a single moment in time. Date objects are based on a time value that is the number of milliseconds since 1 January, 1970`

**Comment by devanshdalal** [comment]
Hi guys, Is the issue still unresolved ? I want to contribute as well.

**Comment by tagawa** [comment]
Hi @devanshdalal. That would be great - thank you for offering!
Feel free to comment here with questions or suggestions, and there's also a forum thread for discussing this Instant Answer (IA): https://forum.duckduckhack.com/t/improve-mdn-javascript-fathead/155/14

And in case you haven't seen it, we have in-depth documentation here: https://docs.duckduckhack.com

Thanks again!

**Comment by devanshdalal** [comment]
Hi guys,

This might seem silly. But I agree with @bfmags' comment about. Because with the latest version of the mdnjs, I am still getting the correct expected output.txt.

`<pre><code>new Date();\nnew Date(value);\nnew Date(dateString);\nnew Date(year, month[, date[, hours[, minutes[, seconds[, milliseconds]]]]]);\n</code></pre>
`

Please, give me any hits what can be wrong in this ?

**Comment by bfmags** [comment]
@devanshdalal Thanks for reviewing the code! I think this is going to be looked at internally (possibly Fathead internal bug), but @MariagraziaAlastra will confirm shortly.

**Comment by MariagraziaAlastra** [comment]
Yup, this looks like an internal issue. 
@devanshdalal would you like to work instead on this issue: [jQuery: Add article aliases (redirects) -- Add, set](https://github.com/duckduckgo/zeroclickinfo-fathead/issues/609)? It's high priority and it would greatly improve coverage for the jQuery IA and overall in the JavaScript search space :smile:
